# Generated by Django 4.1.5 on 2023-04-12 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "department_name",
                    models.CharField(
                        choices=[
                            ("hr", "Hr"),
                            ("backoffice", "Backoffice"),
                            ("developer", "Developer"),
                            ("designer", "Designer"),
                            ("business_development", "Business_Development"),
                            ("admin", "Admin"),
                        ],
                        default="hr",
                        max_length=250,
                    ),
                ),
                (
                    "employee",
                    models.UUIDField(blank=True, default=uuid.uuid4, null=True),
                ),
                (
                    "organization",
                    models.UUIDField(blank=True, default=uuid.uuid4, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
