# Generated by Django 4.1.5 on 2023-04-17 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('job', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('user', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('user_profile', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('shortlisted', models.BooleanField(default=False)),
                ('interview_status', models.CharField(blank=True, max_length=30, null=True)),
                ('result', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'AppliedJobs',
                'ordering': ('created_at',),
            },
        ),
    ]
