# Generated by Django 4.1.7 on 2023-04-17 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZoomMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "meeting_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "meeting_description",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                (
                    "meeting_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "zoom_meeting_link",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("zoom_meeting_password", models.CharField(max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=250, null=True)),
                ("job", models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
