from django.urls import path
from modules.gst import views

app_name = 'gst'

urlpatterns = [
	path('create_category/', 
		views.CategoryCreateAPIView.as_view(), 
		name='create_category'),

	path('create_product/', 
		views.ProductCreateAPIView.as_view(),
		name='create_product'),
	path('product_list', 
		views.ProductListAPIView.as_view(), 
		name='product_list'),
	path('product_details/<slug:slug>', 
		views.ProductRetrieveAPIView.as_view(), 
		name='product_details'),
	path('update_product/<slug:slug>', 
		views.ProductUpdateAPIView.as_view(), 
		name='update_product'),
	path('delete_product/<slug:slug>', 
		views.ProductDestroyAPIView.as_view(), 
		name='delete_product'),

	path('create_customer/', 
		views.CustomerCreateAPIView.as_view(),
		name='create_customer'),
	path('customer_list', 
		views.CustomerListAPIView.as_view(), 
		name='customer_list'),
	path('customer_details/<slug:slug>', 
		views.CustomerRetrieveAPIView.as_view(), 
		name='customer_details'),
	path('update_customer/<slug:slug>', 
		views.CustomerUpdateAPIView.as_view(), 
		name='update_customer'),
	path('delete_customer/<slug:slug>', 
		views.CustomerDestroyAPIView.as_view(), 
		name='delete_customer'),

	path('create_vehicle/', 
		views.VehicleCreateAPIView.as_view(),
		name='create_vehicle'),
	path('vehicle_list', 
		views.VehicleListAPIView.as_view(), 
		name='vehicle_list'),
	path('vehicle_details/<slug:slug>', 
		views.VehicleRetrieveAPIView.as_view(), 
		name='vehicle_details'),
	path('update_vehicle/<slug:slug>', 
		views.VehicleUpdateAPIView.as_view(), 
		name='update_vehicle'),
	path('delete_vehicle/<slug:slug>', 
		views.VehicleDestroyAPIView.as_view(), 
		name='delete_vehicle'),

	path('create_invoice/', 
		views.InvoiceCreateAPIView.as_view(),
		name='create_invoice'),
	path('invoice_list', 
		views.InvoiceListAPIView.as_view(), 
		name='invoice_list'),
	path('invoice_details/<slug:slug>', 
		views.InvoiceRetrieveAPIView.as_view(), 
		name='invoice_details'),
	path('update_invoice/<slug:slug>', 
		views.InvoiceUpdateAPIView.as_view(), 
		name='update_invoice'),
	path('delete_invoice/<slug:slug>', 
		views.InvoiceDestroyAPIView.as_view(), 
		name='delete_invoice')

]